name: nbody
channels:
- conda-forge
dependencies:
  - python=3.6
  - numba # TODO pin versions
  - cupy
  - numpy
  - pytest
  - h5py
  - matplotlib
  - scipy
  - cudatoolkit
  - click
  - hypothesis
  - tqdm
  - pip:
    - black
    - gitpython
