name: nbody
channels:
- conda-forge
- rlehe 
dependencies:
  - python=3.7
  - numba # TODO pin versions
  - numpy
  - pytest
  - openpmd-api
  - matplotlib
  - cudatoolkit
  - click
  - openpmd_viewer
